version: '3'
services:
  server:
    image: api-server
    build:
      context: .
    container_name: api-server
    environment:
      - NODE_ENV=development
      - PORT=8080
      - JWT_SECRET=jwtsecret
    ports:
      - '8080:8080'
    volumes:
      - './src:/app/src'
      - './migrations:/app/migrations'
      - './nest-cli.json:/app/nest-cli.json'
      - './nodemon.json:/app/nodemon.json'
      - './ormconfig.ts:/app/ormconfig.ts'
